# Shared implementation for the 10 R analysis entry points.
args_named <- function() { z <- commandArgs(trailingOnly=TRUE); out <- list(); i <- 1; while(i<=length(z)){ k<-sub("^--","",z[i]); if(i==length(z)||grepl("^--",z[i+1])){out[[k]]<-"TRUE";i<-i+1}else{out[[k]]<-z[i+1];i<-i+2} }; out }
run_analysis <- function(op) {
 a<-args_named(); if(is.null(a$input)||is.null(a$output)) stop("Required: --input file.csv --output path")
 d<-read.csv(a$input,check.names=FALSE,stringsAsFactors=FALSE); out<-a$output
 if(dir.exists(out)||grepl("[/\\\\]$",out)){dir.create(out,recursive=TRUE,showWarnings=FALSE); path<-file.path(out,paste0(op,".csv"))} else {dir.create(dirname(out),recursive=TRUE,showWarnings=FALSE);path<-out}
 pick<-function(explicit,candidates,label,required=TRUE){v<-explicit;if(is.null(v))v<-candidates[candidates%in%names(d)][1];if(is.na(v)||length(v)==0||!v%in%names(d)){if(required)stop(paste("Specify",label,"with its actual column name; available:",paste(names(d),collapse=", ")));return(NULL)};v}
 models<-function(){if(!is.null(a$models))strsplit(a$models,",",fixed=TRUE)[[1]] else intersect(c("Additive","Min","Luk_4D","Composite_Min_Add"),names(d))}
 if(op=="01_validate_files"){r<-data.frame(column=names(d),class=sapply(d,function(x)paste(class(x),collapse="/")),missing=sapply(d,function(x)sum(is.na(x))));write.csv(r,path,row.names=FALSE);cat("rows",nrow(d),"columns",ncol(d),"duplicate_rows",sum(duplicated(d)),"\n")}
 else if(op=="02_descriptive_summary"){x<-d[sapply(d,is.numeric)];if(!ncol(x))stop("No numeric columns"); z<-do.call(rbind,lapply(names(x),function(n){v<-x[[n]];data.frame(column=n,n=sum(!is.na(v)),mean=mean(v,na.rm=TRUE),sd=sd(v,na.rm=TRUE),min=min(v,na.rm=TRUE),median=median(v,na.rm=TRUE),max=max(v,na.rm=TRUE))}));write.csv(z,path,row.names=FALSE)}
 else if(op=="03_aggregate_rubric_dimensions"){cs<-if(!is.null(a$columns))strsplit(a$columns,",",fixed=TRUE)[[1]] else intersect(c("L","I","C","A","Linguistic_Accuracy_L","Intelligibility_I","Communicative_Adequacy_C","Academic_Appropriateness_A"),names(d));if(length(cs)<2||!all(cs%in%names(d)))stop("Provide >=2 valid columns with --columns");x<-as.matrix(d[cs]);if(any(!is.finite(x))||any(x<0|x>1))stop("Dimensions must be finite normalized values in [0,1]");la<-if(is.null(a$lambda))0.5 else as.numeric(a$lambda);if(la<0||la>1)stop("lambda must be in [0,1]");z<-data.frame(mean=rowMeans(x),minimum=apply(x,1,min),lukasiewicz_tnorm=pmax(0,rowSums(x)-(ncol(x)-1)));z$composite_min_add<-la*z$minimum+(1-la)*z$mean;write.csv(z,path,row.names=FALSE)}
 else if(op%in%c("04_model_metrics_vs_human","09_bland_altman")){h<-pick(a$`human-col`,c("Human_Global","Human_Holistic_Criterion"),"--human-col"); ms<-models();if(!length(ms))stop("Pass --models");res<-lapply(ms,function(m){if(!m%in%names(d))stop(paste("Missing",m));ok<-complete.cases(d[[h]],d[[m]]);delta<-d[[m]][ok]-d[[h]][ok];z<-data.frame(model=m,n=sum(ok),MAE=mean(abs(delta)),RMSE=sqrt(mean(delta^2)),bias=mean(delta));if(op=="09_bland_altman")z<-cbind(z,data.frame(mean_pair=mean((d[[m]][ok]+d[[h]][ok])/2),loa_lower=mean(delta)-1.96*sd(delta),loa_upper=mean(delta)+1.96*sd(delta)));z});write.csv(do.call(rbind,res),path,row.names=FALSE)}
 else if(op=="05_subgroup_metrics"){h<-pick(a$`human-col`,c("Human_Global","Human_Holistic_Criterion"),"--human-col");g<-pick(a$`group-col`,c("Profile"),"--group-col");res<-do.call(rbind,lapply(unique(d[[g]]),function(group)do.call(rbind,lapply(models(),function(m){ok<-d[[g]]==group&complete.cases(d[[h]],d[[m]]);e<-d[[m]][ok]-d[[h]][ok];data.frame(group=group,model=m,n=sum(ok),MAE=mean(abs(e)),RMSE=sqrt(mean(e^2)),bias=mean(e))}))));write.csv(res,path,row.names=FALSE)}
 else if(op=="06_bootstrap_mae"){cs<-if(is.null(a$models))names(d)[sapply(d,is.numeric)] else models();res<-do.call(rbind,lapply(cs,function(cn){v<-d[[cn]];data.frame(metric=cn,n=sum(!is.na(v)),mean=mean(v,na.rm=TRUE),sd=sd(v,na.rm=TRUE),q025=quantile(v,.025,na.rm=TRUE),median=median(v,na.rm=TRUE),q975=quantile(v,.975,na.rm=TRUE))}));write.csv(res,path,row.names=FALSE)}
 else if(op=="07_paired_model_tests"){cs<-if(is.null(a$models))names(d)[sapply(d,is.numeric)&grepl("MAE",names(d))] else models();if(length(cs)<2)stop("Pass >=2 paired numeric columns via --models");pairs<-combn(cs,2,simplify=FALSE);res<-do.call(rbind,lapply(pairs,function(p){ok<-complete.cases(d[p]);w<-wilcox.test(d[[p[1]]][ok],d[[p[2]]][ok],paired=TRUE,exact=FALSE);data.frame(model1=p[1],model2=p[2],n=sum(ok),statistic=unname(w$statistic),p_raw=w$p.value)}));res$p_holm<-p.adjust(res$p_raw,"holm");write.csv(res,path,row.names=FALSE)}
 else if(op=="08_sensitivity_lambda"){x<-d[sapply(d,is.numeric)];if(!"Weight_Comm_w"%in%names(d))stop("Provide table including Weight_Comm_w or modify script for actual lambda column");write.csv(x,path,row.names=FALSE)}
 else if(op=="10_publication_figures"){png(if(grepl("\\.png$",out))out else file.path(out,"10_publication_figures.png"),width=1800,height=1100,res=180);x<-d[sapply(d,is.numeric)];if(!is.null(a$models))x<-x[strsplit(a$models,",",fixed=TRUE)[[1]]];if(!ncol(x))stop("No numeric columns to plot");boxplot(x,las=2,main="L2 writing assessment: input distributions",ylab="Observed value");dev.off();cat(out,"\n")}
 else stop(op);if(op!="10_publication_figures")cat(path,"\n")
}
